// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hibehrijqpbqfdakitup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpYmVocmlqcXBicWZkYWtpdHVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTk3MDUsImV4cCI6MjA2NTIzNTcwNX0._UvbsYUikFq7vZy_odTC55U1FL_caf7-UkpVUIClLzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);